### ISSUE TITLE
TCell $TERM not recognised

### ISSUE THREAD

**Issue by lyneca** [akavel/up#15]
TCell seems to need to recognise the value of `$TERM`. There's [an issue over at the TCell repo](https://github.com/gdamore/tcell/issues/118), but it's pretty old. This means that `up` won't work for many people using less-popular terminals (Kitty for me).

A workaround at the moment is to alias:

```bash
$ alias up="TERM=xterm up "
```

Is there some way to bypass this from the `up` side?

**Comment by kalbasit** [comment]
Having the same issue with tmux-256color.

**Comment by akavel** [comment]
Do I understand it correctly, that the result is you're getting an error message `terminal entry not found`, and *up* is not starting? (But starts with the TERM=xterm workaround?) This was not clear to me from your report, only after reading the issue at the tcell repo I started to understand that this is probably what you are trying to tell me. So I wanted to ask to confirm?

I'm also kinda confused now, given that the tcell issue seems to claim it's resolved :/ why did they write so, if the issue still happens? I seem to be using a very new version of tcell :/

**Comment by lyneca** [comment]
Yup, sorry for the unclear report. I'm happy to alias, and having uncommon `$TERM` variables isn't that, well, common, so it's not really that much of an issue.

I think that TCell's solution may have been to just hardcode a bunch of `$TERM` values, which may be why it's not working.

**Comment by kalbasit** [comment]
@akavel in most cases TERM is set. The problem is that it seems to not recognize some of the TERM, or at least TCell is not able to.

**Comment by gunar** [comment]
Same here with `screen-256color-bce`

**Comment by akavel** [comment]
Hmm; from https://github.com/gdamore/tcell/issues/225 and a [comment block in tcell/terminfo/terminfo.go](https://github.com/gdamore/tcell/blob/017915a4d77dabd7af10ab539e618a735d4b9c0a/terminfo/terminfo.go#L789), I gather that support for some terminals is distributed only with tcell sources, as gzipped helper files. That feels like a somewhat weird choice for me at the moment; I wonder why it's not parsed dynamically from OS-provided data for unknown TERMs? It seems like [termbox](https://github.com/nsf/termbox-go) is doing that; I wonder if its code could be adapted somehow to provide support for tcell... or is such dynamic parsing already available somewhere in tcell?

**Comment by akavel** [comment]
I've added a detailed error message, outlining suggested steps that can be taken in order to try and mitigate the issue. I don't currently have good ideas how to resolve this in a better way. If you have some, I'm open to discussion.

Thanks, and I'm sorry I couldn't find a better way for now.

**Comment by masaeedu** [comment]
Thanks for adding that error message @akavel. That's already quite helpful for someone who doesn't understand the inner workings of this terminal stuff; unfortunately I'm trying to figure out what to do about a missing `xterm-24bit` entry, and still can't work out next steps from this error message:

```
error: terminal entry not found
Your terminal code:
        TERM=xterm-24bit
was not found in the database provided by tcell library. Please try checking if
a supplemental database is found for your terminal at one of the following URLs:
        https://github.com/gdamore/tcell/raw/master/terminfo/database/c9/c93be29d
        https://github.com/gdamore/tcell/raw/master/terminfo/database/c9/c93be29d.gz
If yes, download it and save in the following directory:
        $HOME/.tcelldb/c9/
then try running "up" again. If that does not work for you, please first consult:
        https://github.com/akavel/up/issues/15
and if you don't see your terminal code mentioned there, please try asking on:
        https://github.com/gdamore/tcell/issues
Or, you might try changing TERM temporarily to some other value, for example by
running "up" with:
        TERM=xterm up
Good luck!
```

The URLs in the error message don't seem to exist anymore. I realize this may be a case of RTFM, but is there a way to substitute those fixed URLs with some basic information on what's going on and what kind of file(s?) we're trying to retrieve and stick in our `~/.tcelldb/xyz` folder?

**Comment by jean** [comment]
@masaeedu not sure if this helps, but [searching that repo for 'xterm'](https://github.com/gdamore/tcell/search?q=xterm&unscoped_q=xterm) comes up with `{"name":"xterm-24"}`, which looks similar, [here](https://github.com/gdamore/tcell/blob/de7e78efa4a71b3f36c7154989c529dbdf9ae623/terminfo/database/c7/c727e029) and [here](https://github.com/gdamore/tcell/blob/de7e78efa4a71b3f36c7154989c529dbdf9ae623/terminfo/database/e9/e960fa31).
