### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by stefanycesar** [akavel/up#23]
Hello, I'm a designer and I want to know if I can create a logo for your project

**Comment by akavel** [comment]
Uh, oh, wow! Sure, this could be cool :) I've never been in such situation yet, however, and I'm feeling a little bit anxious now, as to whether you'd be ok that I may or may not accept it in the end, and on potentially subjective basis? I've never worked with a designer, so I don't have a good idea how this... umm, works? :)

**Comment by akavel** [comment]
Hm; I don't see much activity here since over a year ago, so closing this for now. I'm happy to reopen if something changes! :) Thanks for your good intentions, I really appreciate them! :) Bless you dear friend
