### ISSUE TITLE
Does it support tailing a file?

### ISSUE THREAD

**Issue by aniket-deole** [akavel/up#32]
I'm not sure if this is the right place to ask. But tailing & using the grep filter on the fly would be super usefull.

Feel free to close the issue if out of place.

**Comment by akavel** [comment]
Hi! It's totally ok to ask! :) Unfortunately, currently I'm not planning to add this feature. It is a cool idea, but as of now, I am not aware how it could be sensibly implemented in the codebase of *up*, I'm afraid. I'll add it to the [ideabook on the wiki](https://github.com/akavel/up/wiki/ideabook) however; it's certainly a cool thought, and maybe some day someone will invent a way to make those ideas work together?

Thanks for your feedback!

**Comment by juanpabloaj** [comment]
@aniket-deole with peco you can do that 

https://github.com/peco/peco

... but in my case, when I use peco with tailing peco consumes all the cpu

**Comment by akavel** [comment]
Uh, by the way, this was kinda obvious to me, but maybe is not so obvious, so just to make sure it's explained: you can do something like below to tail a file:

```console
$ tail -F $FILE | up
```

— though, the limitation of *up*'s fixed buffer size remains.
