### ISSUE TITLE
terminfo and kitty term

### ISSUE THREAD

**Issue by dfischer** [akavel/up#45]
``` terminal code:
        TERM=xterm-kitty
was not found in the database provided by tcell library. Please try checking if
a supplemental database is found for your terminal at one of the following URLs:
        https://github.com/gdamore/tcell/raw/master/terminfo/database/98/98d2a8a0
        https://github.com/gdamore/tcell/raw/master/terminfo/database/98/98d2a8a0.gz
If yes, download it and save in the following directory:
        $HOME/.tcelldb/98/
then try running "up" again. If that does not work for you, please first consult:
        https://github.com/akavel/up/issues/15
and if you don't see your terminal code mentioned there, please try asking on:
        https://github.com/gdamore/tcell/issues
Or, you might try changing TERM temporarily to some other value, for example by
running "up" with:
        TERM=xterm up
Good luck!```

How to get it to work with `xterm-kitty` ? http://www.9bis.net/kitty/

**Comment by akavel** [comment]
Did you try following the instructions as explained above, in the text you quoted? Is something about them unclear?

**Comment by dfischer** [comment]
Running into issues with both `fish shell` and exporting `TERM`. It doesn't seem to want to play nice at all.

**Comment by akavel** [comment]
What issues? What "it"? How specifically "doesn't seem to want to play nice"? I'm afraid it's hard for me to try and help you when I don't really understand the question :( Also, I'm really sorry, but I don't have enough time and resources to be able to install kitty or fish myself for debugging this, so you'd really help me if you could provide explanatory information and context under assumption I'm using a different terminal emulator & shell... Thanks for reporting this issue and caring to further talk about it!

**Comment by akavel** [comment]
I'm marking this as blocked waiting for response; I'm afraid I can't currently proceed without answers & clarifications that would make the issue understandable to me in detail.

**Comment by akavel** [comment]
I think upgrading the `tcell` dependency in go.mod to https://github.com/gdamore/tcell/commit/4e7865679e391b0f1a9296e428edce5eb421790a or newer could auto-resolve this. I will try to do this At Some Point In The Future™, though not yet sure when exactly, as I don't have much time for *up* maintenance recently. And I'd like to add some tests to the codebase before that, to give me some kind of confidence that the upgrade won't break stuff...

**Comment by jeanCarloMachado** [comment]
+1 to this issue. Would be great indeed to upgrade tcell and get kitty out of the box. Amazing project by the way!
