### ISSUE TITLE
Logo time

### ISSUE THREAD

**Issue by thoaionline** [akavel/up#48]
Hi there,

Our team at [GPU Exchange](https://gpu.exchange/) uses this tool a lot and we want to give back to the project.

We sketched together some logo ideas for this (see below). Let us know which one you like most and I'll send over the source file for your future branding use.

Thanks again,

![up_logos](https://user-images.githubusercontent.com/229556/75955216-80e42080-5f09-11ea-9ef1-e6435e819d9c.jpg)

**Comment by anselal** [comment]
Very nice gesture guys, respect !!!

**Comment by akavel** [comment]
Oh, wow, so cool!!!!! ❤️ ❤️ ❤️ Really, that's such a wonderful surprise, and giving me this warm fuzzy feeling... I would like to hug you all, sit close by just relaxing and grinning mindlessly and bathe in waves of radiant love that I am certain must be visibly emanating from you now :) :) :)

Uh oh... yeah right, I shall probably collect myself a bit... at least for a short while... so, if I'm free to say, I seem to apparently love the first one the most by far... on many accounts, though I'm not sure if they are the real reasons, or I'm just rationalizing post fact, but anyway, it definitely makes me smile the most....! Still, I'm already seriously pondering printing them all on some sheet of thick paper, framing them and hanging somewhere on my wall... I'll think about it, also whether to do it for all or just the one; or maybe I'll make it the big one in the center, and put the others below in a line?

Ah, yes, however, I'd kinda like to let myself have one small question here, if I may: one thing that kinda make me a teeny bit... hm... anxious?... is that the outflow from the pipe seemed to me a slight bit... uh, *sewery*... I'm really so overwhelmed and intimidated by your gesture, that I find it really hard to ask of anything, and I'll definitely most happily take it as is if that's the end of the story; however, in case you were feeling so magnanimous as to bear with my pulling it... and also given that's the only time & chance I would have... is there a possibility your amazingly talented artist(s) could try and take one final stab at it, in maybe trying to experiment with whether they fancied exploring some alternative ways of expressing the downwards bit to make it slightly... fresher? 😋 I am not the artist here, so I am certain with such imagination you will find various ways of approaching this, but just to add a pebble to the pile, or to hopefully spark some thunderous brain storms, the one thing I personally managed to think of was a kinda garden hose sprinkler blast when you put a finger on the end... :) but I'm not tied to it; as I say, if you're off of this, I do love the first one quite a lot already; in fact, in the end, I may even still stay with it anyway, if that's ok with you! Especially given the genius observation implied, that I cannot refuse appreciating, that the tool *is* in fact best suited at filtering through truckloads of messy, formless, *shitty* logs........... uhuh...... it's just, everybody likes to have their picture if a tiny teeny bit pimped up... ;P but as I say, I'll let it grow on me, and may even like to keep this metaphor in the end, as a kind of an inside joke.... so, however you feel at answering this! :)

As to some final formal/technical/... inquiries: how can I credit you for the logo? I'd especially love to put some name(s) behind it if I may, it's always cool to feel a personal connection; I'm happy to put even a long list out there, and with many links, and totally with the name of your company too, which I also highly appreciate for sponsoring this and the implicit endorsement of the project's usability :) Also, I've never worked with artists or like, so I have no slightest idea at legal aspects of this; should I be asking you for some kind of formal permission to use it in some specific ways, some "royalty free" stuff, or other complicated "for any purpose" and "derived works" phrases? Say, if I would like to create a black&white version for printing/typesetting, with maybe changed/exaggerated proportions to make it potentially look distinct in tiny sizes?

HUGE thanks again, to all of you!!!

**Comment by thoaionline** [comment]
@akavel lolz, i didn't expect this!

have a look at some the revisions, what do you think?

![revision_2](https://user-images.githubusercontent.com/229556/76085952-334ddd80-6007-11ea-954b-b2587d2e88a7.jpg)

**Comment by akavel** [comment]
Based on the first v1 above, and inspired by ideas in your second post, I'm starting to think about something like below; or just going with the first v1; I think I'll be now trying to decide between the two! ❤️ 

<img src="https://user-images.githubusercontent.com/273837/76129217-11545b00-6007-11ea-9de6-3b6a0e19d300.png" width="50%" />

**Comment by akavel** [comment]
@thoaionline After some discussions with a few people, I would like to finalize the decision on the 1st logo from your 1st set. Again HUGE THANK YOU 😄 😍 🎉  AND TONS OF ❤️ ❤️ ❤️ LOVE! Wrapping this up, is there a chance to get the source file from you, as you suggested in the initial post? If not, I guess I'll go with the initial image, given its generous resolution, but esp. if you have the logo in a vector format, this could prove very useful I think! :)

Thanks again!!!

**Comment by thoaionline** [comment]
@anselal let me locate the source file and send them to you via email over this weekend ;)

**Comment by akavel** [comment]
@thoaionline I added the logo to the readme, with a few extra links at the end of the readme - thanks a lot again!!! 😄 😄 😄
