### ISSUE TITLE
Allow running up with no input

### ISSUE THREAD

**Issue by NightMachinary** [akavel/up#50]
I like to run up to just run grep searches interactively (using `ripgrep` on the current directory).

**Comment by akavel** [comment]
I saw this sentiment expressed also in #33; can you please help me understand if there are reasons why e.g. something like `echo | up` is not working for you? What holds me back on this feature is basically that I'm having concerns about discoverability of the app's core feature being impacted...

**Comment by NightMachinary** [comment]
@akavel Because `up` passes the dummy input to the command, and a lot of commands (including grep) will change their behavior if stdin is present. I don't think discoverability will be affected; If anything, the current marketing seems confusing to me. `up` is essentially a new mode of using a REPL. I think the best summary of what `up` is, is `up makes your commands sticky in any REPL`. Anyhow, adding an option for running with no input, if not advertised upfront, definitely won't change people's first impression of the tool.

**Comment by diego898** [comment]
Would this not be the exact usecase for FZF?
