### ISSUE TITLE
snap package

### ISSUE THREAD

**Issue by LyzardKing** [akavel/up#55]
Hi! I made a quick snap package for up, so that I could easily install/update the program on ubuntu.
It is classic (not confined) so it has access to the system as a normal program.
Are you interested in supporting this? If not can I publish it on the snap store (with a note saying it is unofficial)?

**Comment by akavel** [comment]
Hi @LyzardKing! I don't know much about snap; you're sure welcome to upload this wherever you want, as long as it doesn't violate the rather lax Apache-2.0 license, which is most probably fine with snap. I'm not sure what exactly do you mean by me supporting this; if this requires any future actions from me, I certainly won't be doing them 😅 but people have submitted *up* to various package managers, as listed in the readme, I'm more than OK with that. You're welcome to add an appropriate entry to the readme along the other ones if that makes sense for snap and for you.

**Comment by LyzardKing** [comment]
Cool. I'll run some further tests, and let you know when it's uploaded to the store with the link.
As for the support, being a go program it should be fine, I might need to bother you with help if something breaks, but it should be mostly automated.
Thanks for the quick reply!
